# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1430e2b2562563751093d90bd39b8472a164243c69038eb379bf1aadea1216fa6ec157fdafccecb87bd1670c4f95b7483f5d574ed1c18c2268cf1bf72e271b2

test:
  secret_key_base: d9d8d1a2d91c5ada658eb1b206bebaf33690ed2542d596ca9f6303882f13dc70f2b117002891ff112ee659a10f03aea1c7542457bf2cde97f3536daefd2a51be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
